
-- 샘플 사용자 5명
INSERT INTO users (username, password, email, nickname)
VALUES ('test01', '1234', 'test01@email.com', '스프링마스터'),
       ('test02', '1234', 'test02@email.com', '야근하는개발자'),
       ('test03', '1234', 'test03@email.com', '판교러'      ),
       ('test04', '1234', 'test04@email.com', '코드장인'  ),
       ('test05', '1234', 'test05@email.com', '디버깅요정' );

--  로그인 로그 20건 (최신순, 분 단위 차등)
INSERT INTO user_login_logs (user_id, login_time, success, fail_reason)
VALUES
(1, DATEADD('MINUTE', -19, CURRENT_TIMESTAMP), TRUE , NULL),
(1, DATEADD('MINUTE', -18, CURRENT_TIMESTAMP), FALSE, 'INVALID_PASSWORD'),
(1, DATEADD('MINUTE', -17, CURRENT_TIMESTAMP), TRUE , NULL),
(1, DATEADD('MINUTE', -16, CURRENT_TIMESTAMP), FALSE, 'ACCOUNT_LOCKED'),
(1, DATEADD('MINUTE', -15, CURRENT_TIMESTAMP), TRUE , NULL),
(2, DATEADD('MINUTE', -14, CURRENT_TIMESTAMP), TRUE , NULL),
(2, DATEADD('MINUTE', -13, CURRENT_TIMESTAMP), TRUE , NULL),
(2, DATEADD('MINUTE', -12, CURRENT_TIMESTAMP), FALSE, 'INVALID_PASSWORD'),
(2, DATEADD('MINUTE', -11, CURRENT_TIMESTAMP), TRUE , NULL),
(3, DATEADD('MINUTE', -10, CURRENT_TIMESTAMP), FALSE, 'INVALID_2FA'),
(3, DATEADD('MINUTE',  -9, CURRENT_TIMESTAMP), TRUE , NULL),
(3, DATEADD('MINUTE',  -8, CURRENT_TIMESTAMP), FALSE, 'INVALID_PASSWORD'),
(3, DATEADD('MINUTE',  -7, CURRENT_TIMESTAMP), TRUE , NULL),
(4, DATEADD('MINUTE',  -6, CURRENT_TIMESTAMP), TRUE , NULL),
(4, DATEADD('MINUTE',  -5, CURRENT_TIMESTAMP), TRUE , NULL),
(4, DATEADD('MINUTE',  -4, CURRENT_TIMESTAMP), FALSE, 'ACCOUNT_DISABLED'),
(4, DATEADD('MINUTE',  -3, CURRENT_TIMESTAMP), TRUE , NULL),
(5, DATEADD('MINUTE',  -2, CURRENT_TIMESTAMP), FALSE, 'INVALID_PASSWORD'),
(5, DATEADD('MINUTE',  -1, CURRENT_TIMESTAMP), TRUE , NULL),
(5, DATEADD('MINUTE',   0, CURRENT_TIMESTAMP), FALSE, 'INVALID_2FA');
