server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:devdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: WARN
    org.springframework.batch: INFO
    org.springframework.batch.core.step.tasklet.TaskletStep: WARN