
INSERT INTO users (username, email, password, role)
VALUES
    ('user1', 'hong1@example.com', '1234', 'USER'),
    ('user2', 'hong2@example.com', '1234', 'USER'),
    ('user3', 'hong3@example.com', '1234', 'ADMIN');


-- ------------------------
-- POSTS SAMPLE DATA
-- ------------------------

INSERT INTO posts (title, content, author_id)
VALUES
    ('Spring Boot 캐시 최적화 전략', 'Spring Cache와 Caffeine을 활용한 고성능 캐싱 구조 설계 방법을 소개합니다.', 1),
    ('JPA N+1 문제 해결 가이드', '페치 조인과 배치 사이즈 조절을 통해 N+1 문제를 효율적으로 해결하는 방법.', 1),
    ('Redis vs Caffeine 캐시 비교', '메모리 캐시와 분산 캐시의 장단점을 비교 분석합니다.', 1),
    ('웹 애플리케이션 성능 튜닝 기초', '스레드 풀 설정, DB 커넥션 풀, GC 튜닝 등 주요 성능 요소를 다룹니다.', 2),
    ('Spring Security FilterChain 이해', 'Spring Security의 필터 흐름을 단계별로 분석합니다.', 2),
    ('OAuth2 로그인 내부 동작 방식', 'Authorization Code 흐름을 기반으로 OAuth2 로그인 구조를 설명합니다.', 2),
    ('JPA 영속성 컨텍스트 완전 정복', '1차 캐시, 플러시, dirty checking 개념을 상세히 다룹니다.', 3),
    ('Docker 기반 개발환경 구성', 'Docker Compose를 활용한 로컬 개발환경 자동화 구성 예제.', 3),
    ('MSA 환경에서 API Gateway 선택 기준', 'Nginx, Spring Cloud Gateway, Kong 비교 분석.', 3),
    ('Spring AOP 실무 활용법', '로깅, 트랜잭션, 보안 검증 등 AOP의 실제 활용 사례 정리.', 1),
    ('비동기 처리 CompletableFuture', '멀티스레드 환경에서 CompletableFuture 패턴 활용법.', 1),
    ('Kafka 기본 개념과 활용', '메시지 브로커 Kafka의 핵심 개념과 실사용 예.', 1),
    ('REST API 설계 베스트 프랙티스', 'URI 규칙, 응답 구조, 에러 핸들링 원칙 정리.', 2),
    ('CI/CD 자동화 구축', 'GitHub Actions 기반 지속적 배포 파이프라인 구성.', 2),
    ('JWT 토큰 구조와 보안 고려사항', 'JWT 구조 분석과 보안 취약점 대응방법을 설명합니다.', 2),
    ('DB 인덱스 최적화 전략', '인덱스 구조와 실행계획 분석을 중심으로 성능 개선 전략.', 3),
    ('Spring Batch 대용량 처리', '대량 데이터 배치를 위한 Spring Batch 설계 패턴.', 3),
    ('대규모 서비스 아키텍처 설계', '트래픽 급증 대비 scalable 아키텍처 구성 원칙.', 3),
    ('WebClient 타임아웃 처리', 'Spring WebFlux WebClient의 타임아웃 및 재시도 설정 방법.', 1),
    ('가상 스레드(Virtual Thread) 이해', 'Java Loom 기반 가상 스레드의 성능 이점과 적용법.', 1),
    ('QueryDSL 동적 쿼리 작성법', 'BooleanBuilder와 where 절 조합을 이용한 실용적인 동적 쿼리 예제.', 1),
    ('AWS S3 presigned URL 업로드', 'S3에 안전하게 파일을 업로드하는 presigned URL 방식 설명.', 2),
    ('CloudWatch 로그 분석', 'AWS CloudWatch Logs Insights로 로그 분석하는 방법.', 2),
    ('Lambda와 API Gateway 연동', '서버리스 아키텍처 구성 핵심 개념 설명.', 2),
    ('MySQL 트랜잭션 격리 수준', 'READ COMMITTED, REPEATABLE READ 차이와 실무 적용.', 3),
    ('Spring Retry 적용법', '외부 API 오류 대비 retry/backoff 정책 구성.', 3),
    ('Circuit Breaker 패턴', 'Resilience4j 기반 회로 차단기 패턴 설명.', 3),
    ('ElasticSearch 검색 최적화', '검색 스코어, 토크나이저, 인덱스 튜닝 방식 설명.', 1),
    ('CI/CD와 블루그린 배포', '무중단 배포 전략 중 블루그린 배포 구조 설명.', 1),
    ('Kubernetes Pod 스케줄링', 'NodeSelector, Taint/Toleration, Affinity 설명.', 1),
    ('React 상태 관리 비교', 'Redux, Recoil, Zustand의 장단점을 비교합니다.', 2),
    ('TypeScript 타입 시스템 핵심', 'TS의 구조적 타이핑, 제네릭, 유틸리티 타입 설명.', 2),
    ('프런트엔드 웹 성능 최적화', 'LCP, TTI 개선을 위한 주요 전략 설명.', 2),
    ('AI 모델 서빙 전략', 'GPU, Batch Serving, Async Serving 방식 비교.', 3),
    ('Vector Database 기본', '벡터 검색 구조와 ANN(Approximate Nearest Neighbor) 설명.', 3),
    ('Spring Boot 캐시 최적화 전략', 'Spring Cache와 Caffeine을 활용한 고성능 캐싱 구조 설계 방법을 소개합니다.', 1),
    ('JPA N+1 문제 해결 가이드', '페치 조인과 배치 사이즈 조절을 통해 N+1 문제를 효율적으로 해결하는 방법.', 1),
    ('Redis vs Caffeine 캐시 비교', '메모리 캐시와 분산 캐시의 장단점을 비교 분석합니다.', 1),
    ('웹 애플리케이션 성능 튜닝 기초', '스레드 풀 설정, DB 커넥션 풀, GC 튜닝 등 주요 성능 요소를 다룹니다.', 2),
    ('Spring Security FilterChain 이해', 'Spring Security의 필터 흐름을 단계별로 분석합니다.', 2),
    ('OAuth2 로그인 내부 동작 방식', 'Authorization Code 흐름을 기반으로 OAuth2 로그인 구조를 설명합니다.', 2),
    ('JPA 영속성 컨텍스트 완전 정복', '1차 캐시, 플러시, dirty checking 개념을 상세히 다룹니다.', 3),
    ('Docker 기반 개발환경 구성', 'Docker Compose를 활용한 로컬 개발환경 자동화 구성 예제.', 3),
    ('MSA 환경에서 API Gateway 선택 기준', 'Nginx, Spring Cloud Gateway, Kong 비교 분석.', 3),
    ('Spring AOP 실무 활용법', '로깅, 트랜잭션, 보안 검증 등 AOP의 실제 활용 사례 정리.', 1),
    ('비동기 처리 CompletableFuture', '멀티스레드 환경에서 CompletableFuture 패턴 활용법.', 1),
    ('Kafka 기본 개념과 활용', '메시지 브로커 Kafka의 핵심 개념과 실사용 예.', 1),
    ('REST API 설계 베스트 프랙티스', 'URI 규칙, 응답 구조, 에러 핸들링 원칙 정리.', 2),
    ('CI/CD 자동화 구축', 'GitHub Actions 기반 지속적 배포 파이프라인 구성.', 2),
    ('JWT 토큰 구조와 보안 고려사항', 'JWT 구조 분석과 보안 취약점 대응방법을 설명합니다.', 2),
    ('DB 인덱스 최적화 전략', '인덱스 구조와 실행계획 분석을 중심으로 성능 개선 전략.', 3),
    ('Spring Batch 대용량 처리', '대량 데이터 배치를 위한 Spring Batch 설계 패턴.', 3),
    ('대규모 서비스 아키텍처 설계', '트래픽 급증 대비 scalable 아키텍처 구성 원칙.', 3),
    ('WebClient 타임아웃 처리', 'Spring WebFlux WebClient의 타임아웃 및 재시도 설정 방법.', 1),
    ('가상 스레드(Virtual Thread) 이해', 'Java Loom 기반 가상 스레드의 성능 이점과 적용법.', 1),
    ('QueryDSL 동적 쿼리 작성법', 'BooleanBuilder와 where 절 조합을 이용한 실용적인 동적 쿼리 예제.', 1),
    ('AWS S3 presigned URL 업로드', 'S3에 안전하게 파일을 업로드하는 presigned URL 방식 설명.', 2),
    ('CloudWatch 로그 분석', 'AWS CloudWatch Logs Insights로 로그 분석하는 방법.', 2),
    ('Lambda와 API Gateway 연동', '서버리스 아키텍처 구성 핵심 개념 설명.', 2),
    ('MySQL 트랜잭션 격리 수준', 'READ COMMITTED, REPEATABLE READ 차이와 실무 적용.', 3),
    ('Spring Retry 적용법', '외부 API 오류 대비 retry/backoff 정책 구성.', 3),
    ('Circuit Breaker 패턴', 'Resilience4j 기반 회로 차단기 패턴 설명.', 3),
    ('ElasticSearch 검색 최적화', '검색 스코어, 토크나이저, 인덱스 튜닝 방식 설명.', 1),
    ('CI/CD와 블루그린 배포', '무중단 배포 전략 중 블루그린 배포 구조 설명.', 1),
    ('Kubernetes Pod 스케줄링', 'NodeSelector, Taint/Toleration, Affinity 설명.', 1),
    ('React 상태 관리 비교', 'Redux, Recoil, Zustand의 장단점을 비교합니다.', 2),
    ('TypeScript 타입 시스템 핵심', 'TS의 구조적 타이핑, 제네릭, 유틸리티 타입 설명.', 2),
    ('프런트엔드 웹 성능 최적화', 'LCP, TTI 개선을 위한 주요 전략 설명.', 2),
    ('AI 모델 서빙 전략', 'GPU, Batch Serving, Async Serving 방식 비교.', 3),
    ('Vector Database 기본', '벡터 검색 구조와 ANN(Approximate Nearest Neighbor) 설명.', 3),
    ('Spring Boot 캐시 최적화 전략', 'Spring Cache와 Caffeine을 활용한 고성능 캐싱 구조 설계 방법을 소개합니다.', 1),
    ('JPA N+1 문제 해결 가이드', '페치 조인과 배치 사이즈 조절을 통해 N+1 문제를 효율적으로 해결하는 방법.', 1),
    ('Redis vs Caffeine 캐시 비교', '메모리 캐시와 분산 캐시의 장단점을 비교 분석합니다.', 1),
    ('웹 애플리케이션 성능 튜닝 기초', '스레드 풀 설정, DB 커넥션 풀, GC 튜닝 등 주요 성능 요소를 다룹니다.', 2),
    ('Spring Security FilterChain 이해', 'Spring Security의 필터 흐름을 단계별로 분석합니다.', 2),
    ('OAuth2 로그인 내부 동작 방식', 'Authorization Code 흐름을 기반으로 OAuth2 로그인 구조를 설명합니다.', 2),
    ('JPA 영속성 컨텍스트 완전 정복', '1차 캐시, 플러시, dirty checking 개념을 상세히 다룹니다.', 3),
    ('Docker 기반 개발환경 구성', 'Docker Compose를 활용한 로컬 개발환경 자동화 구성 예제.', 3),
    ('MSA 환경에서 API Gateway 선택 기준', 'Nginx, Spring Cloud Gateway, Kong 비교 분석.', 3),
    ('Spring AOP 실무 활용법', '로깅, 트랜잭션, 보안 검증 등 AOP의 실제 활용 사례 정리.', 1),
    ('비동기 처리 CompletableFuture', '멀티스레드 환경에서 CompletableFuture 패턴 활용법.', 1),
    ('Kafka 기본 개념과 활용', '메시지 브로커 Kafka의 핵심 개념과 실사용 예.', 1),
    ('REST API 설계 베스트 프랙티스', 'URI 규칙, 응답 구조, 에러 핸들링 원칙 정리.', 2),
    ('CI/CD 자동화 구축', 'GitHub Actions 기반 지속적 배포 파이프라인 구성.', 2),
    ('JWT 토큰 구조와 보안 고려사항', 'JWT 구조 분석과 보안 취약점 대응방법을 설명합니다.', 2),
    ('DB 인덱스 최적화 전략', '인덱스 구조와 실행계획 분석을 중심으로 성능 개선 전략.', 3),
    ('Spring Batch 대용량 처리', '대량 데이터 배치를 위한 Spring Batch 설계 패턴.', 3),
    ('대규모 서비스 아키텍처 설계', '트래픽 급증 대비 scalable 아키텍처 구성 원칙.', 3),
    ('WebClient 타임아웃 처리', 'Spring WebFlux WebClient의 타임아웃 및 재시도 설정 방법.', 1),
    ('가상 스레드(Virtual Thread) 이해', 'Java Loom 기반 가상 스레드의 성능 이점과 적용법.', 1),
    ('QueryDSL 동적 쿼리 작성법', 'BooleanBuilder와 where 절 조합을 이용한 실용적인 동적 쿼리 예제.', 1),
    ('AWS S3 presigned URL 업로드', 'S3에 안전하게 파일을 업로드하는 presigned URL 방식 설명.', 2),
    ('CloudWatch 로그 분석', 'AWS CloudWatch Logs Insights로 로그 분석하는 방법.', 2),
    ('Lambda와 API Gateway 연동', '서버리스 아키텍처 구성 핵심 개념 설명.', 2),
    ('MySQL 트랜잭션 격리 수준', 'READ COMMITTED, REPEATABLE READ 차이와 실무 적용.', 3),
    ('Spring Retry 적용법', '외부 API 오류 대비 retry/backoff 정책 구성.', 3),
    ('Circuit Breaker 패턴', 'Resilience4j 기반 회로 차단기 패턴 설명.', 3),
    ('ElasticSearch 검색 최적화', '검색 스코어, 토크나이저, 인덱스 튜닝 방식 설명.', 1),
    ('CI/CD와 블루그린 배포', '무중단 배포 전략 중 블루그린 배포 구조 설명.', 1),
    ('Kubernetes Pod 스케줄링', 'NodeSelector, Taint/Toleration, Affinity 설명.', 1),
    ('React 상태 관리 비교', 'Redux, Recoil, Zustand의 장단점을 비교합니다.', 2),
    ('TypeScript 타입 시스템 핵심', 'TS의 구조적 타이핑, 제네릭, 유틸리티 타입 설명.', 2),
    ('프런트엔드 웹 성능 최적화', 'LCP, TTI 개선을 위한 주요 전략 설명.', 2),
    ('AI 모델 서빙 전략', 'GPU, Batch Serving, Async Serving 방식 비교.', 3),
    ('Vector Database 기본', '벡터 검색 구조와 ANN(Approximate Nearest Neighbor) 설명.', 3);

