-- 기존 테이블 제거
DROP TABLE IF EXISTS shipping_history CASCADE;
DROP TABLE IF EXISTS product_files CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS file_repository CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- users: 회원 정보
CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP                 DEFAULT CURRENT_TIMESTAMP,
    username    VARCHAR(50)      NOT NULL UNIQUE,
    email       VARCHAR(100)     NOT NULL UNIQUE,
    address     VARCHAR(500),
    password    VARCHAR(255)     NOT NULL,
    role        VARCHAR(20)      NOT NULL
);

-- products: 상품 정보
CREATE TABLE products
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP                 DEFAULT CURRENT_TIMESTAMP,
    name           VARCHAR(200)     NOT NULL,
    description    TEXT,
    price          DECIMAL(10, 2)  NOT NULL,
    quantity       INT             NOT NULL
);

-- file_repository: 파일 저장 전용
CREATE TABLE file_repository
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    original_filename VARCHAR(255)     NOT NULL,
    rename_filename   VARCHAR(255)     NOT NULL,
    file_type         VARCHAR(50)      NOT NULL    -- IMAGE, THUMBNAIL, ETC 등
);

-- product_files
CREATE TABLE product_files
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT        NOT NULL,
    file_id     BIGINT        NOT NULL,
    sort_order  INT,

    CONSTRAINT fk_pf_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_pf_file
        FOREIGN KEY (file_id)
            REFERENCES file_repository (id)
            ON DELETE CASCADE

);

-- orders
CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status         VARCHAR(20)      NOT NULL,
    user_id        BIGINT           NOT NULL,
    product_id     BIGINT           NOT NULL,
    quantity       INT              NOT NULL,
    unit_price     DECIMAL(10, 2)   NOT NULL,
    total_amount   DECIMAL(12, 2)   NOT NULL,
    shipping_addr  VARCHAR(500),

    CONSTRAINT fk_order_user
        FOREIGN KEY (user_id)
            REFERENCES users (id),

    CONSTRAINT fk_order_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
);


CREATE TABLE shipping_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_id    BIGINT           NOT NULL,
    status      VARCHAR(20)      NOT NULL,
    message     VARCHAR(500),

    CONSTRAINT fk_shipping_order
        FOREIGN KEY (order_id)
            REFERENCES orders (id)
);
